### ISSUE TITLE
How to switch LED on flora color sensor board

### ISSUE THREAD

**Issue by DF9BI** [adafruit/Adafruit_TCS34725#14]
Hello,

I just got an adafruit Flora Color Sensor board, this small circular one which has only GND, VCC, SCL and SDA pins.

Unfortunately, I could not find a schematic for this board, so i could not figure out, how to turn off the LED via the FET on the board. It looks like the gate of the FET is connected to the INT-Pin of the TCS34725, but I am not sure.

Now my question is, how can I switch of the LED? Can this be done by a command that is written to the TCS34725 so that it pulls the INT-Pin low?

**Comment by ladyada** [comment]
https://github.com/adafruit/Adafruit_TCS34725/blob/master/examples/colorview/colorview.ino#L58

**Comment by ladyada** [comment]
Github is not used for tech support - please use the forums for tech support
