### ISSUE TITLE
License.txt missing

### ISSUE THREAD

**Issue by 3rwww1** [adafruit/Adafruit_TCS34725#20]
The README refers to a license.txt file that appears to be missing. I'd like to redistribute this library in my open-source project. For the moment I'm assuming BSD 3-Clause and copyright to Adafruit Industries. but a clear statement would be a lot better.

Thanks! :smile:

**Comment by ladyada** [comment]
hiya license is here while ya wait
https://github.com/adafruit/Adafruit_TCS34725/blob/master/Adafruit_TCS34725.h
thanks :)

**Comment by hoffmannjan** [comment]
Now It's added :).
