### ISSUE TITLE
[update] I2C/SDA/SCL pin on different boards

### ISSUE THREAD

**Issue by xtr3mz** [adafruit/Adafruit_TCS34725#28]
If you encounter not working problem on non uno board, check this:

https://www.arduino.cc/en/Reference/Wire

Board | I2C / TWI pins

Uno, Ethernet | A4 (SDA), A5 (SCL)
Mega2560 | 20 (SDA), 21 (SCL)
Leonardo | 2 (SDA), 3 (SCL)
Due | 20 (SDA), 21 (SCL), SDA1, SCL1

**Comment by ladyada** [comment]
thanks!
