### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by Darksouhls** [adafruit/Adafruit_TCS34725#43]
Hii, I dont know if im supposed to write it here, but I'm a student doing an engineers study. I have the TCS34725 sensor but I have a Xmega and have to code in C. I also have to get an C++ code and rewrite it as C as part of the project. I would like to get some help to fix this. I have 6 days to finish this.

**Comment by caternuson** [comment]
Sorry, this is not the place. This is where you would post issues for using this library with Arduino.

If you want general help, you can try posting the forums:
https://forums.adafruit.com/
or on discord:
http://adafru.it/discord

For either location, help is not guaranteed. But someone in the community may be willing to help.
