### ISSUE TITLE
Not working on Arduino Uno WIFI Rev 2

### ISSUE THREAD

**Issue by samuelkl** [adafruit/Adafruit_TCS34725#50]
I am having problems using the library with an Arduino Uno WIFI Rev 2. The sensor is found while doing an I2C scan. However, the library finds no sensor. Can you help me troubleshoot this?

**Comment by tyeth** [comment]
Hi @samuelkl, hopefully you've already got this resolved, but if not, then it is possible with a lot of our drivers to pass in the sensor address + I2C bus. 
https://github.com/adafruit/Adafruit_TCS34725/blob/master/Adafruit_TCS34725.h#L201
See the begin function takes an address then TwoWire object, so use the same i2c object that you've been using for the i2c scan (Maybe Wire1 or a custom TwoWire object defined for your set of pins).

Please reopen this issue if you need more assistance
