### ISSUE TITLE
documentation incorrect

### ISSUE THREAD

**Issue by kuldeepdhaka** [adafruit/Adafruit_TCS34725#8]
https://github.com/adafruit/Adafruit_TCS34725/blob/master/Adafruit_TCS34725.cpp#L293

**Comment by birbilis** [comment]
what error does it have exactly?

**Comment by kuldeepdhaka** [comment]
"Converts the raw R/G/B values to lux"

AND

"This only uses RGB ... how can we integrate clear or calculate lux"
"based exclusively on clear since this might be more reliable?"
